# This is a basic workflow to help you get started with Actions

name: Generate Schema Docs and Publish to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1

      # Auto commits minified files to the repository
      # Ignore it if you don't want to commit the files to the repository 
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          directory: script
          commit_message: "Github Action: Auto Minified JS files"
          branch: ${{ github.ref }}
      
      - name: Add badges to README.md
        uses: wow-actions/add-badges@v1
        env:
          repo_url: ${{ github.event.repository.html_url }}
          repo_name: ${{ github.event.repository.name }}
          repo_owner: ${{ github.event.repository.owner.login }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          badges: |
            [
              {
                "badge": "https://img.shields.io/github/license/${{ env.repo_owner }}/${{ env.repo_name }}?style=flat-rounded",
                "alt": "MIT License",
                "link": "${{ env.repo_url }}/blob/main/LICENSE"
              },
              {
                "badge": "https://img.shields.io/badge/language-JavaScript-blue.svg?style=flat-rounded",
                "alt": "Language"
              },
              {
                "badge": "https://img.shields.io/badge/PRs-Welcome-brightgreen.svg?style=flat-rounded",
                "alt": "PRs Welcome",
                "link": "${{ env.repo_url }}/pulls"
              }
            ]
